# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
          {id: 0, size: 0.1651},
          {id: 1, size: 0.1651},
          {id: 2, size: 0.1651},
          {id: 3, size: 0.1651},
          {id: 4, size: 0.1651},
          {id: 5, size: 0.1651},
          {id: 6, size: 0.1651},
          {id: 7, size: 0.1651},
          {id: 8, size: 0.1651},
          {id: 9, size: 0.1651},
          {id: 10, size: 0.1651},
          {id: 11, size: 0.1651},
          {id: 12, size: 0.1651},
          {id: 13, size: 0.1651},
          {id: 14, size: 0.1651},
          {id: 15, size: 0.1651},
          {id: 16, size: 0.1651},
          {id: 17, size: 0.1651},
          {id: 18, size: 0.1651},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'warthog_1',
      layout:
        [
          {id: 5, size: 0.17, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0000, qx: 0.0000, qy: 0.0000, qz: 0.0000},
          {id: 1, size: 0.17, x: -0.3347, y: -0.1445, z: -0.2081, qw: 0.9995, qx: -0.0261, qy: 0.0134, qz: -0.0109},
          {id: 0, size: 0.17, x: -0.3341, y: 0.1647, z: -0.3509, qw: 0.9605, qx: -0.2777, qy: 0.0006, qz: 0.0179},
          {id: 7, size: 0.17, x: 0.5010, y: 0.0086, z: -0.0020, qw: 0.9942, qx: -0.0323, qy: -0.0954, qz: 0.0386},
          {id: 4, size: 0.17, x: -0.0021, y: 0.2142, z: -0.1197, qw: 0.9493, qx: -0.3140, qy: -0.0075, qz: 0.0082},
          {id: 2, size: 0.17, x: 0.9277, y: -0.0993, z: -0.1765, qw: 0.9916, qx: -0.0935, qy: -0.0818, qz: 0.0364},
          {id: 3, size: 0.17, x: 0.9130, y: 0.2295, z: -0.3135, qw: 0.9669, qx: -0.2477, qy: -0.0606, qz: -0.0124},
          {id: 6, size: 0.17, x: 0.4940, y: 0.2477, z: -0.0743, qw: 0.9572, qx: -0.2750, qy: -0.0895, qz: -0.0070}
        ]
    }
  ]
